- name: Configure Sender
  hosts: sender
  remote_user: admin
  roles:
    - sender
  vars:
    sender_address: 10.0.0.1
    reflector_address: 10.0.0.2

- name: Configure Reflector
  hosts: reflector
  remote_user: admin
  roles:
    - reflector
  vars:
    reflector_address: 10.0.0.2

